### ISSUE TITLE
comparison to textmodel_nb from quanteda

### ISSUE THREAD

**Issue by jwijffels** [mskogholt/fastNaiveBayes#1] opened 2019-03-27 10:34 UTC
Thanks for making this available. Appreciate it very much that this package only has the stats and Matrix packages as dependencies. Have you compared the timing and basic metrics of accuracy to the textmodel_nb from the quanteda package which has a similar functionality?
thanks again!

**Comment by martinskogholt** [comment] 2019-03-28 16:14
Hi, thank you very much for the feedback, I'm glad you like it. To be honest I was unaware of this implementation, so I have not, but I will definetively have a look this weekend and add this to the vignette!

**Comment by jwijffels** [comment] 2019-03-29 08:50
That would be great to have as a comparison.

**Comment by majkamichal** [comment] 2019-03-31 19:37
You could also make comparison to the `naivebayes` package.

**Comment by majkamichal** [comment] 2019-03-31 22:31
Could you show the code with speed comparisons? It looks to me like you run the model only once and then reported results. In your Vignette, the speed difference between your Bernoulli implementation and the naivebayes implementation was very big: your implementation was (3655.7ms / 158.5ms) = 23.06 times faster than in the`naivebayes` package. I was surprised a bit by this and made some speed comparison as well.

In the (dirty) code below you can find artificially enlarged `BreastCancer` dataset with 28,704 rows and  1120 columns (I don't have the data with tweets). Using this artificial data, I compared the speed of  `predict.fastNaiveBayes.bernoulli` (model trained with sparse = FALSE, because it was supposed to be faster according to your speedtest) and `naivebayes::predict.naivebayes`. After 50 runs on my MacBook Air from 2013, it turned out that your predict function is on average 2.25 faster.

```
Unit: relative
                                           expr      min
 predict(model2, newdata = big, type = "class") 1.000000
   predict(nb2, newdata = big2, type = "class") 2.805724
              lq        mean     median          uq         max    neval
 1.000000 1.000000 1.000000 1.00000 1.000000    50
 2.730584 2.248806 2.508518 1.91643 1.827656    50
```


I also benchmarked the train functions: on average,  the `naive_bayes` function is about 6.2 times slower  than `fastNaiveBayes.bernoulli`:

```
Unit: relative
                                                                   expr
 fastNaiveBayes.bernoulli(x = big, y = y2, laplace = 1, sparse = FALSE)
                             naive_bayes(x = big2, y = y2, laplace = 1)
           min              lq        mean     median            uq         max     neval
 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    50
 7.329044 7.082344 6.204234 6.382932 5.843052 5.805817    50
```

Both functions are written fully in Base R. The `naive_bayes` function was never optimised for speed compared to the predict function. For clarity: `big2` is the same dataset but instead of being a matrix, it is a data.frame with factors - naivebayes requires features to be either character/factor/logical in order to use Bernoulli.



```
library(microbenchmark)
library(fastNaiveBayes)
library(naivebayes)

require(mlbench)

# Load BreastCancer data
data(BreastCancer)
dim(BreastCancer)
levels(BreastCancer$Class)
head(BreastCancer)

# Bernoulli dummy example
data_mat <- BreastCancer[, c("Class", "Cl.thickness", "Cell.size", "Cell.shape", "Marg.adhesion")]
col_counter <- ncol(data_mat) + 1
for (i in 2:ncol(data_mat)) {
    for (val in unique(data_mat[, i])) {
        data_mat[, col_counter] <- ifelse(data_mat[, i] == val, 1, 0)
        col_counter <- col_counter + 1
    }
}

y <- data_mat[, "Class"]
data_mat <- data_mat[, setdiff(colnames(data_mat), c(
    "Class", "Cl.thickness", "Cell.size",
    "Cell.shape", "Marg.adhesion"
))]

data_mat <- as.matrix(data_mat)

# I don't have any dataset with tweets but enlarging BreastCancer data
# should do.

# Let's make the data longer (add more rows):

data_test <- data_mat[401:nrow(data_mat), ]
data_test_big <- rbind(data_test,data_test,data_test,data_test,data_test,data_test)

# It takes a while (at least on my MacBook air 13)
big <- cbind(data_test_big,data_test_big,data_test_big,data_test_big)
big <- cbind(big,big,big,big,big,big,big)

big <- rbind(big,big,big,big,big,big,big,big,big,big,big,big,big,big,big,big)

# In naivebayes the Bernoulli applies to factors/characters/logical
big2 <- big
mode(big2) <- "character"
big2 <- as.data.frame(big2)
dim(big2) # 28704 x 1120

y2 <- sample(c("benign", "malignant"), nrow(big), replace = TRUE)

model2 <- fastNaiveBayes.bernoulli(x = big, y = y2, laplace = 1, sparse = FALSE)
nb2 <- naive_bayes(x = big2, y = y2, laplace = 1)

# Comparison: ------------------------------------------------------------------

# predict functions
microbenchmark(
  predict(model2, newdata = big,  type = "class"),
  predict(nb2,    newdata = big2, type = "class"),
  times = 50,
  unit = "relative"
)


# train functions
microbenchmark(
  fastNaiveBayes.bernoulli(x = big, y = y2, laplace = 1, sparse = FALSE),
  naive_bayes(x = big2, y = y2, laplace = 1),
  times = 50,
  unit = "relative"
)
```


Best,
Michal

**Comment by martinskogholt** [comment] 2019-04-02 08:59
Hey guys,

First off, I added a more extensive execution time comparison to a lot of different implementations in the Vignette (I believe it should be on CRAN already). @jwijffels this includes a comparison to the quanteda package.

@majkamichal, thank you for double checking and sharing the code. I will try the speed comparison on the same enlarged breastcancer set and rather report these results in the vignette, with code examples to make it a bit more transparent as to how these differences are established in terms of execution times. The tweets data is a csv I grabbed from Kaggle at some point in time, which makes it hard to reproduce the results. 

There is one thing I should note, which is that in my speed comparison as reported in the vignette I did both the estimation of the model and the predict function in a single statement, for example 'predict(fastNaiveBayes.bernoulli(x = big, y = y2, laplace = 1, sparse = FALSE), newdata = big)'. I don't know how these relative measurements then multiply, but that could have something to do with it. 

I will keep you updated on new results, I expect to do it this weekend!

**Comment by majkamichal** [comment] 2019-04-02 18:49
I think, it would be easier for you to simulate data. Something like this would give you full control over the dimensions of the dataset:


```
nrow <- 20000
ncol <- 1000
n_repeats <- 50

set.seed(2)
data <- matrix(sample(c(TRUE, FALSE), size = nrow * ncol, replace = TRUE),
                nrow = nrow, ncol = ncol)
colnames(data) <- paste0("V", seq_len(ncol))
y <- factor(sample(c("a", "b"), size = nrow, replace = TRUE))

data1 <- data
data2_nb <- data
mode(data1) <- "numeric"
mode(data2_nb) <- "character"
data2_nb <- as.data.frame(data)


fnb <- fastNaiveBayes.bernoulli(x = data1, y = y, laplace = 1, sparse = FALSE)
nb <- naive_bayes(x = data2_nb, y = y, laplace = 1)


# Overall
microbenchmark(
  predict(fastNaiveBayes.bernoulli(x = data1, y = y, laplace = 1, sparse = FALSE), newdata = data1,  type = "class"),
  predict(naive_bayes(x = data2_nb, y = y, laplace = 1), newdata = data2_nb, type = "class"),
  times = n_repeats,
  unit = "relative"
)

# Predict functions
microbenchmark(
  predict(fnb, newdata = data1,  type = "class"),
  predict(nb, newdata = data2_nb, type = "class"),
  times = n_repeats,
  unit = "relative"
)

# Train functions
microbenchmark(
  fastNaiveBayes.bernoulli(x = data1, y = y, laplace = 1, sparse = FALSE),
  naive_bayes(x = data2_nb, y = y, laplace = 1),
  times = n_repeats,
  unit = "relative"
)
```

You could make a graph that would depict how  the relative and absolute differences develop with growing number of rows and the other graph with the growing number of columns.

Best,
Michal

**Comment by majkamichal** [comment] 2019-04-04 19:02
Sorry for spamming but speedtests sound so much fun :)


Again a simulated dataset but this time something less time consuming: 20,000 rows and 1000 columns. The parameter `sparse = TRUE` makes your function a bit slower. There were some issues in your Bernoulli predict function when predicting class labels - some error which doesn't happen every time when the data has a big number of columns (you should reproduce it and take a look on it - something with "max.col" and "ties"). First I took a look at the case when predict functions were outputting probabilities. It turned out that when `sparse = TRUE` your Bernoulli was minimally slower (50 repetitions). It was a bit weird so I run it two times:

```
Unit: relative
                                                                                                                expr
 predict(fastNaiveBayes.bernoulli(x = data1, y = y, laplace = 1,      sparse = TRUE), newdata = data1, type = "raw")
                      predict(naive_bayes(x = data2_nb, y = y, laplace = 1), newdata = data2_nb,      type = "prob")
      min       lq     mean   median       uq      max neval
 1.025751 1.046258 1.033938 1.044022 1.027924 1.046943    50
 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    50
```

```
Unit: relative
                                                                                                                expr
 predict(fastNaiveBayes.bernoulli(x = data1, y = y, laplace = 1,      sparse = TRUE), newdata = data1, type = "raw")
                      predict(naive_bayes(x = data2_nb, y = y, laplace = 1), newdata = data2_nb,      type = "prob")
     min       lq     mean   median       uq       max neval
 1.01354 1.044758 1.034093 1.047921 1.025572 0.9380271    50
 1.00000 1.000000 1.000000 1.000000 1.000000 1.0000000    50
```

Then I re-run the same code with the difference that `sparse=FALSE` and `type = "class"` and expected your implementation to be faster. Indeed, it turned out to be faster but on average 2.83 times, say 3 times.  Honestly, the factor of 20 in the vignette doesn't look legit - it some cases it may happen but it is not a proper number to report.

```
Unit: relative
                                                                                                                   expr
 predict(fastNaiveBayes.bernoulli(x = data1, y = y, laplace = 1,      sparse = FALSE), newdata = data1, type = "class")
                        predict(naive_bayes(x = data2_nb, y = y, laplace = 1), newdata = data2_nb,      type = "class")
      min       lq     mean  median       uq
 1.000000 1.000000 1.000000 1.00000 1.000000
 2.982569 2.929709 2.833232 2.81844 2.828243
 max neval
 1.000000    50
 2.631091    50
```
 Code:

```
nrow <- 20000
ncol <- 1000
n_repeats <- 50

set.seed(2)
data <- matrix(sample(0:1, size = nrow * ncol, replace = TRUE),
                nrow = nrow, ncol = ncol)
colnames(data) <- paste0("V", seq_len(ncol))
y <- factor(sample(c("a", "b"), size = nrow, replace = TRUE))

data1 <- data
data2_nb <- data
mode(data2_nb) <- "character"
data2_nb <- as.data.frame(data)

# Overall: sparse = TRUE and type = "raw" (2x)
microbenchmark(
  predict(fastNaiveBayes.bernoulli(x = data1, y = y, laplace = 1, sparse = TRUE), newdata = data1,  type = "raw"),
  predict(naive_bayes(x = data2_nb, y = y, laplace = 1), newdata = data2_nb, type = "prob"),
  times = n_repeats,
  unit = "relative"
)

# Overall: sparse = FALSE and type = "class"
microbenchmark(
  predict(fastNaiveBayes.bernoulli(x = data1, y = y, laplace = 1, sparse = FALSE), newdata = data1,  type = "class"),
  predict(naive_bayes(x = data2_nb, y = y, laplace = 1), newdata = data2_nb, type = "class"),
  times = n_repeats,
  unit = "relative"
)

``` 


Best regards,
Michal

**Comment by jwijffels** [comment] 2019-04-05 07:34
@martinskogholt Thank you for the incorporation of the extra comparisons in the vignette. Really appreciate this package!

**Comment by mskogholt** [comment] 2019-04-06 14:29
Hi to the both of you again!

I had a look today and I added even more comparisons in the vignette, now also with Gaussian event model in place. I made the tweets data available in the package, both raw text and converted to a document-term matrix. Furthermore, I included the code that I used to benchmark the performance in the Vignette as well. 

@majkamichal, I believe I was passing a numerical matrix to the 'naivebayes' package which would mean it would be using the gaussian event model, which might explain the difference. The speed up is now 8 times faster compared to naivebayes on the tweets data that I used. 

Indeed, setting the parameter sparse = TRUE, when passing a matrix that is actually dense it will slow it down considerably. This is because in the function the matrix is cast to a sparse dgCMatrix and moreover the simulated data is actually 50% dense. 

What I find intriguing is that when I run your exact code, I get these results:

Unit: relative
                                                                                                                   expr
 predict(fastNaiveBayes.bernoulli(x = data1, y = y, laplace = 1,      sparse = FALSE), newdata = data1, type = "class")
                        predict(naive_bayes(x = data2_nb, y = y, laplace = 1), newdata = data2_nb,      type = "class")
      min       lq     mean   median       uq      max neval
  1.00000  1.00000  1.00000  1.00000  1.00000  1.00000     5
 15.96843 15.40642 14.09532 15.80703 13.96638 11.02353     5

Which is a speed up of 14 times. Which R version are you using?

**Comment by majkamichal** [comment] 2019-04-06 16:26
I run your code from the vignette but with a dataframe containing the character vectors and naive_bayes was 2.8x slower on my Macbook Air 2013. I am using R `3.4.3`. I will update R.
By the way, Gaussian NB is slower than Bernoulli NB in naivebayes.


```
Unit: relative
                  expr      min       lq     mean   median
        fastNaiveBayes 1.000000 1.000000 1.000000 1.000000
 fastNaiveBayes_sparse 1.581334 1.727982 1.776326 1.872947
            naivebayes 2.747116 2.788129 2.787033 2.854687
       uq      max neval
 1.000000 1.000000    10
 1.862318 1.767120    10
 2.798482 2.681929    10
```

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] data.table_1.10.4-3  klaR_0.6-12         
 [3] MASS_7.3-47          bnlearn_4.4.1       
 [5] naivebayes_0.9.5     quanteda_1.4.1      
 [7] fastNaiveBayes_1.1.2 microbenchmark_1.4-6
 [9] Matrix_1.2-15        e1071_1.7-1         
[11] tm_0.7-6             NLP_0.2-0           

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1         pillar_1.3.1       compiler_3.4.3    
 [4] class_7.3-14       tools_3.4.3        stopwords_0.9.0   
 [7] lubridate_1.7.4    tibble_2.1.1       gtable_0.2.0      
[10] lattice_0.20-35    pkgconfig_2.0.2    rlang_0.3.3       
[13] fastmatch_1.1-0    rstudioapi_0.8     parallel_3.4.3    
[16] stringr_1.4.0      dplyr_0.8.0.1      xml2_1.2.0        
[19] combinat_0.0-8     grid_3.4.3         tidyselect_0.2.5  
[22] glue_1.3.1         R6_2.4.0           spacyr_1.0        
[25] ggplot2_3.1.0.9000 purrr_0.3.2        magrittr_1.5      
[28] scales_1.0.0       assertthat_0.2.1   colorspace_1.3-2  
[31] stringi_1.4.3      lazyeval_0.2.1     RcppParallel_4.4.0
[34] munsell_0.5.0      slam_0.1-43        crayon_1.3.4    
```





```
rm(list=ls())
###################### LIBRARIES ###########################
library(tm) #used for text mining 
library(e1071) #this package includes the naive Bayes algorithm
library(Matrix)
library(microbenchmark)
library(e1071)
library(fastNaiveBayes)
library(quanteda)
library(naivebayes)
library(bnlearn)
library(klaR)
library(data.table)

############################ Timing Script ################
results <- NULL

# Bernoulli Event Model
tweets <- fastNaiveBayes::tweetsDTM


y_var <- tweets$airline_sentiment
y_var <- as.factor(ifelse(y_var=='negative','negative','non-negative'))
tweets <- tweets[,2:ncol(tweets)]
tweets[tweets>1] <- 1

tweets <- tweets[,which(colSums(tweets)!=0)]
tweets <- tweets[,which(colSums(tweets)!=nrow(tweets))]

tweet_mat <- as.matrix(tweets)
sparse_tweets <- Matrix(as.matrix(tweet_mat), sparse = TRUE)

for(i in 1:ncol(tweets)){
    tweets[[i]] <- as.factor(tweets[[i]])
}

# # BNLearn
# bn_tweets <- cbind(y_var, tweets)
# colnames(bn_tweets)[1] <- 'y_var'

# # Quanteda
# dfm <- as.dfm(tweet_mat)

tweets_nb <- tweet_mat
mode(tweets_nb) <- "character"
tweets_nb <- as.data.frame(tweet_mat, stringsAsFactors = FALSE)
format(object.size(tweets_nb), "Mb")


(res <- microbenchmark(
    fastNaiveBayes = predict(fastNaiveBayes.bernoulli(tweet_mat, y_var, laplace = 1), tweet_mat),
    fastNaiveBayes_sparse = predict(fastNaiveBayes.bernoulli(sparse_tweets, y_var, laplace = 1), sparse_tweets),
    naivebayes = predict(naivebayes::naive_bayes(tweets_nb, y_var, laplace = 1), newdata = tweets_nb),
    times = 10,
    unit = "relative"
))

```

**Comment by majkamichal** [comment] 2019-04-06 16:49
After updating R to `3.5.3` `naive_bayes` seems to be about 8x slower.  However, on `3.4.3` it was "only" about 3x. So on average 5.5x. It looks like In the newer R version linear algebra got a nice boost.

**Comment by majkamichal** [comment] 2019-04-06 20:58
For the `tweets ` dataset `naive_bayes` is about 8.8x slower.  For datasets with big number of rows and small number of columns the difference is smaller. For two columns and 500K rows your implementation can be even 1.2x slower. With increasing number of columns your implementation is faster but doesn't seem to scale on `Mac`  that well in case of big number of rows. 

To my eyes it is not orders of magnitude:  for 500K rows and 50 columns `naive_bayes` Bernoulli gets about `~2.9x` slower:


```
Unit: relative
                                                                              expr
 pred_fnb <- predict(fastNaiveBayes.bernoulli(x = X11, y = y),      newdata = X11)
                          pred_nb <- predict(naive_bayes(x = X1_nb, y = y), X1_nb)
      min       lq     mean   median       uq      max neval
 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    50
 3.616766 3.207349 2.846351 2.958204 2.747721 1.863715    50
```


With 500K rows and 100 columns `naive_bayes` gets about 3x slower:


```
Unit: relative
                                                                              expr
 pred_fnb <- predict(fastNaiveBayes.bernoulli(x = X11, y = y),      newdata = X11)
                          pred_nb <- predict(naive_bayes(x = X1_nb, y = y), X1_nb)
      min       lq     mean   median       uq      max neval
 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    50
 3.456127 3.215493 2.924615 3.004013 2.849485 2.035285    50
```

For 500K rows and 200 columns `~2.24` slower: 

```
Unit: relative
                                                                              expr
 pred_fnb <- predict(fastNaiveBayes.bernoulli(x = X11, y = y),      newdata = X11)
                          pred_nb <- predict(naive_bayes(x = X1_nb, y = y), X1_nb)
      min       lq     mean   median       uq      max neval
 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    50
 2.795575 2.559293 2.236947 2.362398 2.000956 1.438867    50
```

For 500K rows and 300 columns it was `~1.85x` slower: (dataset size  `572.4 Mb` )

```
Unit: relative
                                                                              expr
 pred_fnb <- predict(fastNaiveBayes.bernoulli(x = X11, y = y),      newdata = X11)
                          pred_nb <- predict(naive_bayes(x = X1_nb, y = y), X1_nb)
      min       lq     mean   median       uq      max neval
 1.000000 1.000000 1.000000 1.000000 1.000000 1.000000    50
 2.335768 2.055331 1.854078 1.856006 1.724073 1.722964    50
```

For small number of rows and high number of columns your implementation scales better,  for `500`rows and `5000` columns the speedup was about `17` fold. It should be since your implementation is based on simple matrix multiplications. Again, I am using the `macOS`. On windows it may look a bit different but also not dramatically different.

For `5000` rows and `500` columns the speedup was about `5.44x` with your implementation.
For `5000` rows and `5000` columns: speedup `~3.4`

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] data.table_1.12.0    klaR_0.6-14         
 [3] MASS_7.3-51.1        bnlearn_4.4.1       
 [5] naivebayes_0.9.5     quanteda_1.4.3      
 [7] fastNaiveBayes_1.1.2 microbenchmark_1.4-6
 [9] Matrix_1.2-15        e1071_1.7-1         
[11] tm_0.7-6             NLP_0.2-0           

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1         lubridate_1.7.4    lattice_0.20-38   
 [4] prettyunits_1.0.2  class_7.3-15       ps_1.3.0          
 [7] assertthat_0.2.1   rprojroot_1.3-2    digest_0.6.18     
[10] mime_0.6           slam_0.1-45        R6_2.4.0          
[13] plyr_1.8.4         backports_1.1.3    highr_0.8         
[16] ggplot2_3.1.0      pillar_1.3.1       rlang_0.3.3       
[19] lazyeval_0.2.2     curl_3.3           miniUI_0.1.1.1    
[22] rstudioapi_0.10    callr_3.2.0        combinat_0.0-8    
[25] desc_1.2.0         devtools_2.0.1     stringr_1.4.0     
[28] questionr_0.7.0    munsell_0.5.0      shiny_1.2.0       
[31] httpuv_1.5.1       compiler_3.5.3     spacyr_1.0        
[34] pkgconfig_2.0.2    pkgbuild_1.0.3     htmltools_0.3.6   
[37] tidyselect_0.2.5   tibble_2.1.1       later_0.8.0       
[40] crayon_1.3.4       dplyr_0.8.0.1      withr_2.1.2       
[43] grid_3.5.3         xtable_1.8-3       gtable_0.3.0      
[46] magrittr_1.5       scales_1.0.0       RcppParallel_4.4.2
[49] cli_1.1.0          stringi_1.4.3      promises_1.0.1    
[52] fs_1.2.7           remotes_2.0.2      xml2_1.2.0        
[55] stopwords_0.9.0    fastmatch_1.1-0    tools_3.5.3       
[58] glue_1.3.1         purrr_0.3.2        processx_3.3.0    
[61] pkgload_1.0.2      parallel_3.5.3     colorspace_1.4-1  
[64] sessioninfo_1.1.1  memoise_1.1.0      usethis_1.4.0     
```

```
library(fastNaiveBayes)
library(naivebayes)
library(microbenchmark)

vars <- 50 # then changed to 100, 200 and 300
rows <- 500000
y <- sample(letters[1:2], rows, TRUE)

# Only categorical variables

X11 <- matrix(sample(0:1, vars * rows, TRUE, prob = c(0.6,0.4)), ncol = vars)
colnames(X11) <- paste0("V", 1:ncol(X11))
X1_nb <- X11

mode(X1_nb) <- "character"
X1_nb <- as.data.frame(X1_nb)

(res <- microbenchmark(
    pred_fnb <- predict(fastNaiveBayes.bernoulli(x = X11, y = y), newdata = X11),
    pred_nb <- predict(naive_bayes(x = X1_nb, y = y), X1_nb),
    times = 50,
    unit = "relative"
))

```
I got sick - high fever and headache, cannot sleep so speed-tests :D 

Best,
Michal

**Comment by martinskogholt** [comment] 2019-04-08 08:08
Hey Michal,

Very interesting, I had not expected an update of R to have such a significant impact. 

The results are interesting, as well. It makes sense, as I assume you use a loop over de columns with a vectorized function call?

**Comment by mskogholt** [comment] 2019-04-08 21:40
I had a look and removed some inefficiencies from the bernoulli model, it should now be around 2 times faster than it was! (NOTE: If you install from github, not on CRAN yet)

**Comment by mskogholt** [comment] 2019-04-09 16:49
Wauw, the speed up is now huge (300x) for sparse matrices (on sparse data of course)

**Comment by mskogholt** [comment] 2019-04-09 16:54
I'm closing this issue by the way, but thank you both for all the effort!

**Closed as completed by mskogholt** 2019-04-09 16:54 UTC
